You agree, through your use of this bulletin, that you will not post any material which is false, defamatory, inaccurate, abusive, vulgar, hateful, harassing, obscene, profane, sexually oriented, threatening, invasive of a person's privacy, adult material, or otherwise in violation of any International or United States Federal law. You also agree not to post any copyrighted material unless you own the copyright or you have written consent from the owner of the copyrighted material. Spam, flooding, advertisements, chain letters, pyramid schemes, and solicitations are also forbidden on this bulletin.

Please remember that this bulletin owner or staff do not actively monitor the posted messages and the bulletin owner or staff are not responsible for the content contained within. We do not warrant the accuracy, completeness, or usefulness of any information presented. The posted messages express the views of the author, and not necessarily the views of this bulletin, its staff, its subsidiaries, or the bulletin's owner. Anyone who feels that a posted message is objectionable is encouraged to notify an administrator or moderator of this bulletin immediately. The staff and the owner of this bulletin reserve the right to remove objectionable content, if we determine that removal is necessary. This is a manual process, however, please realize that we may not be able to remove or edit particular messages immediately.

You remain solely responsible for the content of your posted messages. Furthermore, you agree to indemnify and hold harmless the owners of this bulletin, any related websites to this bulletin, its staff, and its subsidiaries. The owners of this bulletin also reserve the right to reveal your identity or any other related information collected on this bulletin in the event of a formal complaint or legal action arising from any situation caused by your use of this bulletin.

After you register and login to this bulletin, you will be able to fill out a detailed profile. It is your responsibility to present clean and accurate information. Any information the bulletin owner or staff determines to be inaccurate or vulgar in nature will be removed, with or without prior notice. Appropriate sanctions may be applicable.

Note, emails may be disabled at this website. If emails are disabled then you can register without an email address and the email address validation will be disabled. Your account will contain a uniquely identifiable username, a personal password used for logging into your account and a personal valid email address. You have the option of what information in your account is publicly displayed. Furthermore, within your account, you have the option to opt-in or opt-out of automatically generated emails.

Your password is ciphered by a hash, so that it is secure. However, you should not reuse the same password across a number of different websites. Your password is the means of accessing your account at this bulletin, so please guard it carefully. Under no circumstance will the owner or staff ask you for your password. Should you forget your password for your account, you can use the “forgot password” link. This process will ask you to submit your username and your email address, then a new password will be sent to your email address. If sending out emails are disabled within this bulletin then the new password will be displayed at this bulletin.